[package]
name = "dontuse-this-001"
description = "just for learning cargo crate push"
license = "MIT"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
