[package]
name = "ch07_defining-modules-restaurant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dontuse-this-001 = "0.1.1"
rand = "0.8.5"
